create index idx_productname on product(product_name);

select * from orders;
Select * from product;


-- 4. Products with more repeat orders than new orders
-- 5. Top 3 products based on number of orders
-- 6. Total revenue from 'new' and 'repeat' orders separately
-- 7. Month-wise total revenue

-- 1. Fetch order details along with product name and price
-- SELECT o.o_id , o.order_date , o.order_type  , p.product_name , p.price , p.product_id
-- FROM orders o 
-- INNER JOIN product p ON o.product_id = p.product_id;

-- 2. Total revenue generated by each product
SELECT p.product_id, p.product_name, SUM(p.price) AS total_revenue
FROM product p 
INNER JOIN orders o ON o.product_id = p.product_id
GROUP BY p.product_id;

-- 3. Products that have never been ordered
SELECT p.product_name, p.product_id , o.product_id
FROM product p
LEFT JOIN orders o ON o.product_id = p.product_id
WHERE o.product_id IS NULL;

--Create a function to add two numbers
CREATE OR REPLACE FUNCTION add_number(a INT , b INT )
RETURNS INT
AS $$
BEGIN 

RETURN a+b;
END ;
$$ LANGUAGE plpgsql;

select add_number(20,25);

---- create a function that takes the product name as input and returns the price

CREATE OR REPLACE FUNCTION get_prodprice(prod_name VARCHAR )
-- RETURNS VARCHAR
RETURNS NUMERIC
AS $$
DECLARE prod_price NUMERIC;
BEGIN 
	SELECT price into prod_price from product where product_name = prod_name;
	RETURN prod_price;
 -- RETURN (SELECT price from product where product_name = prod_name);

 END;
 $$ LANGUAGE plpgsql

SELECT get_prodprice('Pen');

DROP FUNCTION get_prodprice_table(character varying)

--create a function that takes product name as input and return the proce and return table
CREATE OR REPLACE FUNCTION get_prodprice_table(prod_name VARCHAR )
RETURNS TABLE(id INT , name varchar(50))
AS $$
BEGIN 
	RETURN QUERY SELECT product_id , product_name from product where product_name = prod_name;
 END;
 $$ LANGUAGE plpgsql

SELECT * FROM get_prodprice_table('Pen');

--wrrite a procedure that takes product fields as input and add a new row in product table

CREATE OR REPLACE PROCEDURE add_product(prod_name VARCHAR , prod_desc VARCHAR, prod_price NUMERIC , prod_category VARCHAR)
AS $$
BEGIN

 INSERT INTO product (product_name, product_desc, price, product_category)
    VALUES (prod_name, prod_desc, prod_price, prod_category);

END;
$$ LANGUAGE plpgsql;


call add_product('PS5' , 'Best game', 50000.00 , 'ELECTRONICS');

select * from orders;
Select * from product;

--write a procedure that takes prod_id and discounted price as input
-- and apply discounted price in all given prod ids
CREATE OR REPLACE PROCEDURE get_discounted_product(prod_id INT ,discount_rate NUMERIC)
AS $$
BEGIN

    UPDATE product SET price = price - (price * discount_rate)
    WHERE product_id = prod_id;

END;
$$ LANGUAGE plpgsql;

call get_discounted_product(21, 0.1);

  -- UPDATE product SET price = 100
  --   WHERE product_id = 21;

----write a procedure that takes prod_id and discounted price as input as array
-- and apply discounted price in all given prod ids
CREATE OR REPLACE PROCEDURE get_discounted_product_array(prod_id INT[] ,discount_rate NUMERIC)
AS $$
BEGIN

    UPDATE product SET price = price - (price * discount_rate)
    WHERE product_id = ANY(prod_id);

END;
$$ LANGUAGE plpgsql;
call get_discounted_product_array(ARRAY[21,10,15] , 0.1);


CREATE TABLE accounts (
id SERIAL PRIMARY KEY,
name varchar(100),
balance NUMERIC
);

CREATE TABLE account_audit (
account_id INT,
old_balance NUMERIC,
new_balance NUMERIC,
changed_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--Trigger function 
create or replace function log_trigger_function()
returns trigger
as $$
begin 
insert into account_audit (account_id,old_balance,new_balance)
values (old.id,old.balance,new.balance);
 return new;
 end;
 $$ language plpgsql;


 --trigger
 create trigger balance_update_trigger
 after update on accounts
 for each row 
 when(old.balance is distinct from new.balance)
 execute function log_trigger_function();


 --insert account
 insert into account_audit(account_id,old_balance,new_balance) values 
 (2,200,500);

 select * from account_audit 
 select * from accounts

 update accounts set balance = 10000 where id = 1
--explain